#!/bin/bash

export scripts="/home/max/scripts/"

export dots="/home/max/dotfiles"

export proj="/home/max/projects"

export nodc="/home/max/projects/nodc/nodc-modules"

export nag="/home/max/projects/nag-parent/nag"

export nodsible="/home/max/projects/nodc/lfs/nodc/setup/ansible"

export nagsible="/home/max/projects/nag-parent/nag/setup/ansible"
